using System.ComponentModel.DataAnnotations;
using AiBusinessWorkflow.Api.Models;
using FluentAssertions;

namespace AiBusinessWorkflow.Tests.Unit.Models;

public class BusinessProcessValidationTests
{
    private static List<ValidationResult> ValidateModel(BusinessProcess process)
    {
        var context = new ValidationContext(process);
        var results = new List<ValidationResult>();
        Validator.TryValidateObject(process, context, results, validateAllProperties: true);
        return results;
    }

    private static BusinessProcess CreateValidProcess() => new()
    {
        Name = "Test Process",
        Description = "A valid test process description",
        InputData = "Some valid input data",
        Goal = "A valid goal statement"
    };

    [Fact]
    public void ValidProcess_ShouldPassValidation()
    {
        var process = CreateValidProcess();
        var results = ValidateModel(process);
        results.Should().BeEmpty();
    }

    [Fact]
    public void Name_WhenEmpty_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Name = string.Empty;
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Name"));
    }

    [Fact]
    public void Name_WhenTooShort_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Name = "AB";
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Name"));
    }

    [Fact]
    public void Name_WhenTooLong_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Name = new string('A', 201);
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Name"));
    }

    [Fact]
    public void Name_AtMinLength_ShouldPassValidation()
    {
        var process = CreateValidProcess();
        process.Name = "ABC";
        var results = ValidateModel(process);
        results.Should().NotContain(r => r.MemberNames.Contains("Name"));
    }

    [Fact]
    public void Name_AtMaxLength_ShouldPassValidation()
    {
        var process = CreateValidProcess();
        process.Name = new string('A', 200);
        var results = ValidateModel(process);
        results.Should().NotContain(r => r.MemberNames.Contains("Name"));
    }

    [Fact]
    public void Description_WhenEmpty_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Description = string.Empty;
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Description"));
    }

    [Fact]
    public void Description_WhenTooShort_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Description = "Short";
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Description"));
    }

    [Fact]
    public void Description_WhenTooLong_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Description = new string('A', 2001);
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Description"));
    }

    [Fact]
    public void InputData_WhenEmpty_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.InputData = string.Empty;
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("InputData"));
    }

    [Fact]
    public void InputData_WhenTooShort_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.InputData = "AB";
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("InputData"));
    }

    [Fact]
    public void Goal_WhenEmpty_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Goal = string.Empty;
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Goal"));
    }

    [Fact]
    public void Goal_WhenTooShort_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Goal = "AB";
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Goal"));
    }

    [Fact]
    public void Goal_WhenTooLong_ShouldFailValidation()
    {
        var process = CreateValidProcess();
        process.Goal = new string('A', 1001);
        var results = ValidateModel(process);
        results.Should().Contain(r => r.MemberNames.Contains("Goal"));
    }

    [Fact]
    public void Id_ShouldBeAutoGenerated()
    {
        var process = new BusinessProcess();
        process.Id.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void AllFieldsEmpty_ShouldFailMultipleValidations()
    {
        var process = new BusinessProcess
        {
            Name = string.Empty,
            Description = string.Empty,
            InputData = string.Empty,
            Goal = string.Empty
        };
        var results = ValidateModel(process);
        results.Should().HaveCountGreaterOrEqualTo(4);
    }
}
