using System.ComponentModel.DataAnnotations;
using AiBusinessWorkflow.Api.Models;
using FluentAssertions;

namespace AiBusinessWorkflow.Tests.Unit.Models;

public class CustomerProfileValidationTests
{
    private static List<ValidationResult> ValidateModel(CustomerProfile profile)
    {
        var context = new ValidationContext(profile);
        var results = new List<ValidationResult>();
        Validator.TryValidateObject(profile, context, results, validateAllProperties: true);
        return results;
    }

    private static CustomerProfile CreateValidProfile() => new()
    {
        CompanyName = "Test Company",
        Industry = "Technology",
        EmployeeCount = 100,
        AnnualRevenue = 5000000m,
        ContactName = "John Doe",
        ContactEmail = "john@test.com",
        AccountAge = "2 years",
        PaymentHistory = "Always on time payments",
        Activities = new List<CustomerActivity>
        {
            new()
            {
                Type = "Meeting",
                Date = "2024-01-15",
                Description = "Quarterly business review meeting",
                Outcome = "Positive feedback"
            }
        }
    };

    [Fact]
    public void ValidProfile_ShouldPassValidation()
    {
        var profile = CreateValidProfile();
        var results = ValidateModel(profile);
        results.Should().BeEmpty();
    }

    [Fact]
    public void CustomerId_ShouldBeAutoGenerated()
    {
        var profile = new CustomerProfile();
        profile.CustomerId.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void CompanyName_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.CompanyName = string.Empty;
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("CompanyName"));
    }

    [Fact]
    public void CompanyName_WhenTooShort_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.CompanyName = "AB";
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("CompanyName"));
    }

    [Fact]
    public void CompanyName_WhenTooLong_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.CompanyName = new string('A', 201);
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("CompanyName"));
    }

    [Fact]
    public void CompanyName_AtMinLength_ShouldPassValidation()
    {
        var profile = CreateValidProfile();
        profile.CompanyName = "ABC";
        var results = ValidateModel(profile);
        results.Should().NotContain(r => r.MemberNames.Contains("CompanyName"));
    }

    [Fact]
    public void CompanyName_AtMaxLength_ShouldPassValidation()
    {
        var profile = CreateValidProfile();
        profile.CompanyName = new string('A', 200);
        var results = ValidateModel(profile);
        results.Should().NotContain(r => r.MemberNames.Contains("CompanyName"));
    }

    [Fact]
    public void Industry_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.Industry = string.Empty;
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("Industry"));
    }

    [Fact]
    public void Industry_WhenTooShort_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.Industry = "A";
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("Industry"));
    }

    [Fact]
    public void ContactName_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.ContactName = string.Empty;
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("ContactName"));
    }

    [Fact]
    public void ContactEmail_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.ContactEmail = string.Empty;
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("ContactEmail"));
    }

    [Fact]
    public void AccountAge_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.AccountAge = string.Empty;
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("AccountAge"));
    }

    [Fact]
    public void PaymentHistory_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.PaymentHistory = string.Empty;
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("PaymentHistory"));
    }

    [Fact]
    public void PaymentHistory_WhenTooShort_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.PaymentHistory = "AB";
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("PaymentHistory"));
    }

    [Fact]
    public void Activities_WhenEmpty_ShouldFailValidation()
    {
        var profile = CreateValidProfile();
        profile.Activities = new List<CustomerActivity>();
        var results = ValidateModel(profile);
        results.Should().Contain(r => r.MemberNames.Contains("Activities"));
    }

    [Fact]
    public void AllFieldsEmpty_ShouldFailMultipleValidations()
    {
        var profile = new CustomerProfile
        {
            CompanyName = string.Empty,
            Industry = string.Empty,
            ContactName = string.Empty,
            ContactEmail = string.Empty,
            AccountAge = string.Empty,
            PaymentHistory = string.Empty,
            Activities = new List<CustomerActivity>()
        };
        var results = ValidateModel(profile);
        results.Should().HaveCountGreaterOrEqualTo(6);
    }
}
