using System.ComponentModel.DataAnnotations;
using AiBusinessWorkflow.Api.Models;
using FluentAssertions;

namespace AiBusinessWorkflow.Tests.Unit.Models;

public class OpportunityValidationTests
{
    private static List<ValidationResult> ValidateModel(Opportunity opportunity)
    {
        var context = new ValidationContext(opportunity);
        var results = new List<ValidationResult>();
        Validator.TryValidateObject(opportunity, context, results, validateAllProperties: true);
        return results;
    }

    private static Opportunity CreateValidOpportunity() => new()
    {
        AccountName = "Test Account",
        DealValue = 50000m,
        Stage = "Proposal",
        ExpectedCloseDate = "2024-06-30",
        CompetitorInfo = "Competitor analysis details here",
        Notes = "Some notes about this opportunity",
        Activities = new List<OpportunityActivity>
        {
            new()
            {
                Type = "Meeting",
                Date = "2024-01-15",
                Description = "Initial discovery call with stakeholders",
                ContactPerson = "Jane Smith"
            }
        }
    };

    [Fact]
    public void ValidOpportunity_ShouldPassValidation()
    {
        var opportunity = CreateValidOpportunity();
        var results = ValidateModel(opportunity);
        results.Should().BeEmpty();
    }

    [Fact]
    public void OpportunityId_ShouldBeAutoGenerated()
    {
        var opportunity = new Opportunity();
        opportunity.OpportunityId.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void AccountName_WhenEmpty_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.AccountName = string.Empty;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("AccountName"));
    }

    [Fact]
    public void AccountName_WhenTooShort_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.AccountName = "AB";
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("AccountName"));
    }

    [Fact]
    public void AccountName_WhenTooLong_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.AccountName = new string('A', 201);
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("AccountName"));
    }

    [Fact]
    public void DealValue_WhenZero_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.DealValue = 0;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("DealValue"));
    }

    [Fact]
    public void DealValue_WhenNegative_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.DealValue = -100m;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("DealValue"));
    }

    [Fact]
    public void DealValue_WhenPositive_ShouldPassValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.DealValue = 0.01m;
        var results = ValidateModel(opportunity);
        results.Should().NotContain(r => r.MemberNames.Contains("DealValue"));
    }

    [Fact]
    public void Stage_WhenEmpty_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.Stage = string.Empty;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("Stage"));
    }

    [Fact]
    public void ExpectedCloseDate_WhenEmpty_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.ExpectedCloseDate = string.Empty;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("ExpectedCloseDate"));
    }

    [Fact]
    public void CompetitorInfo_WhenEmpty_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.CompetitorInfo = string.Empty;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("CompetitorInfo"));
    }

    [Fact]
    public void CompetitorInfo_WhenTooShort_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.CompetitorInfo = "AB";
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("CompetitorInfo"));
    }

    [Fact]
    public void Notes_WhenEmpty_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.Notes = string.Empty;
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("Notes"));
    }

    [Fact]
    public void Notes_WhenTooShort_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.Notes = "AB";
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("Notes"));
    }

    [Fact]
    public void Activities_WhenEmpty_ShouldFailValidation()
    {
        var opportunity = CreateValidOpportunity();
        opportunity.Activities = new List<OpportunityActivity>();
        var results = ValidateModel(opportunity);
        results.Should().Contain(r => r.MemberNames.Contains("Activities"));
    }

    [Fact]
    public void AllFieldsEmpty_ShouldFailMultipleValidations()
    {
        var opportunity = new Opportunity
        {
            AccountName = string.Empty,
            DealValue = 0,
            Stage = string.Empty,
            ExpectedCloseDate = string.Empty,
            CompetitorInfo = string.Empty,
            Notes = string.Empty,
            Activities = new List<OpportunityActivity>()
        };
        var results = ValidateModel(opportunity);
        results.Should().HaveCountGreaterOrEqualTo(6);
    }
}
